name = "painter-decorator-site"
compatibility_date = "2026-07-22"
main = "worker/index.js"
keep_vars = true

[observability]
enabled = true

[assets]
directory = "."
binding = "ASSETS"
not_found_handling = "404-page"
html_handling = "auto-trailing-slash"

[[d1_databases]]
binding = "DB"
database_name = "painter-decorator-invoices"
database_id = "23dbb381-6b9a-4a4a-869d-add5159e5fc0"
