name = "painter-decorator-site"
compatibility_date = "2024-11-01"
main = "worker/index.js"

[assets]
directory = "."
binding = "ASSETS"
not_found_handling = "404-page"
html_handling = "auto-trailing-slash"

[[d1_databases]]
binding = "DB"
database_name = "painter-decorator-invoices"
database_id = "23dbb381-6b9a-4a4a-869d-add5159e5fc0"
migrations_dir = "migrations"
